// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AccountResponse = { id: string, display_name: string, username: string, auth_type: string, key_path: string | null, created_at: string, updated_at: string, };
