// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiscoveredPlugin = { name: string, description: string, version: string, plugin_type: string, source: string, path: string, loaded: boolean, };
