// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Progress payload emitted as `update-progress` events during download.
 */
export type DownloadProgress = { downloaded: number, total: number | null, };
