// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SavedTunnel } from "./SavedTunnel";
import type { ServerEntry } from "./ServerEntry";
import type { ServerFolder } from "./ServerFolder";

/**
 * Portable export format — contains servers (with folders) and tunnels.
 * Passwords and absolute key paths are intentionally excluded.
 */
export type ExportPayload = { version: number, folders: Array<ServerFolder>, ungrouped: Array<ServerEntry>, tunnels: Array<SavedTunnel>, };
