// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A file entry returned from SFTP or local filesystem operations.
 */
export type FileEntry = { name: string, is_dir: boolean, size: number, modified: number | null, permissions: string | null, };
