// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GeneratedKeyResponse = { id: string, algorithm: string, fingerprint: string, comment: string, private_path: string, public_path: string, created_at: string, };
