// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Keyboard shortcuts exposed to the frontend.
 */
export type KeyboardShortcuts = { toggle_right_panel: string, toggle_left_panel: string, toggle_bottom_panel: string, split_vertical: string, split_horizontal: string, close_pane: string, rename_tab: string, };
