// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type KeyGenResponse = { fingerprint: string, public_key: string, algorithm: string, private_path: string, public_path: string, };
