// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metadata for a registered plugin panel.
 */
export type PanelInfo = { plugin_name: string, panel_name: string, location: string, icon: string | null, widgets_json: string, };
