// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A menu item registered by a plugin.
 */
export type PluginMenuItem = { plugin: string, menu: string, label: string, action: string, keybind: string | null, };
