// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SavedTunnel = { id: string, label: string, 
/**
 * Legacy field — `user@host:port` identifying the SSH server for this tunnel.
 */
session_key: string, 
/**
 * New reference to a `ServerEntry` by ID.
 */
server_entry_id?: string | null, local_port: number, remote_host: string, remote_port: number, auto_start: boolean, };
