// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Layout state sent to the frontend on load.
 */
export type SavedLayout = { window_width: number, window_height: number, ssh_panel_width: number, ssh_panel_visible: boolean, files_panel_width: number, files_panel_visible: boolean, bottom_panel_visible: boolean, };
