// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServerEntry } from "./ServerEntry";
import type { ServerFolder } from "./ServerFolder";

export type ServerListResponse = { folders: Array<ServerFolder>, ungrouped: Array<ServerEntry>, ssh_config: Array<ServerEntry>, };
