// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServerEntry } from "./ServerEntry";

export type ServerFolder = { id: string, name: string, expanded: boolean, entries: Array<ServerEntry>, };
