// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ServerEntry = { id: string, label: string, host: string, port: number, user?: string | null, 
/**
 * "key" or "password".
 */
auth_method?: string | null, key_path?: string | null, vault_account_id?: string | null, 
/**
 * Raw proxy command (e.g., `ssh -W %h:%p bastion`). `%h` and `%p` are expanded.
 */
proxy_command?: string | null, 
/**
 * SSH jump host (converted to `ssh -W %h:%p <jump>` at connect time).
 */
proxy_jump?: string | null, };
