// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TerminalDisplayConfig = { font_family: string, font_size: number, cursor_style: string, cursor_blink: boolean, scroll_sensitivity: number, };
