// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransferKind } from "./TransferKind";
import type { TransferStatus } from "./TransferStatus";

export type TransferProgress = { transfer_id: string, kind: TransferKind, status: TransferStatus, bytes_transferred: number, total_bytes: number, file_name: string, error: string | null, };
