// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lightweight summary of an available update, safe to send to the frontend.
 */
export type UpdateInfo = { version: string, body: string | null, };
